### ISSUE TITLE
ie8报错

### ISSUE THREAD

**Issue by nickrogit** [NervJS/nerv-webpack-boilerplate#2]
ie8报错，贴图链接

网页错误详细信息

用户代理: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; qdesk 2.5.1277.202; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)
时间戳: Wed, 28 Mar 2018 02:27:36 UTC

消息: 语法错误
行: 9763
字符: 1
代码: 0
URI: http://localhost:10088/js/es5-polyfill.js

消息: 缺少标识符、字符串或数字
行: 203
字符: 5
代码: 0
URI: http://localhost:10088/js/index.js

**Comment by luckyadam** [comment]
@Littly

**Comment by nickrogit** [comment]
clone最新代码运行ie8还是不支持，截图放到百度云链接了。
dev：
https://pan.baidu.com/s/1SlEnt0sdM7Mdd8EPJcNQMQ
https://pan.baidu.com/s/1BCLR6usp2oT3w9qqGDtHtg
build：
https://pan.baidu.com/s/1QikqTPy4YrMXlTi-bXYmdg

**Comment by nokisnojok** [comment]
ie报错，打包之后代码里面有`` ie没办法执行

**Comment by dai875939260** [comment]
还是因为ie8 Object.defineProperty有不同的行为吧

**Comment by AlexStacker** [comment]
用`yarn build`后的竟然神奇的可以在ie8下跑起来了。

**Comment by luckyadam** [comment]
@AlexStacker 是啊，要编译后才能在IE8下运行，预览不支持的~

**Comment by AlexStacker** [comment]
看上面的报错里带`localhost`，应该是dev模式下报错的`URI: http://localhost:10088/js/es5-polyfill.js`

**Comment by luckyadam** [comment]
@AlexStacker 嗯嗯~dev模式是不能在IE8下跑的

**Comment by luckyadam** [comment]
@nickrogit  请执行 `yarn build` 后试试

**Comment by nickrogit** [comment]
@AlexStacker 这都能被你发现，历害~

**Comment by nickrogit** [comment]
@luckyadam 好的，谢谢

**Comment by nickrogit** [comment]
@luckyadam @AlexStacker 大神们为什么我重新下载这个demo，编译后在ie下看还是会报错呢？
https://pan.baidu.com/s/1Vr-jXZoQvqDYASICsuac1Q

**Comment by nickrogit** [comment]
@AlexStacker 跑是跑起来了，点击交互时还是报错。。。

**Comment by AlexStacker** [comment]
@nickrogit 我的没有碰到这样的错，直接跑起来了，你的也是直接下载build吗？
