### ISSUE TITLE
我build后浏览器没任何内容输出

### ISSUE THREAD

**Issue by twins49** [NervJS/nerv-webpack-boilerplate#5]
我yarn 安装完各种依赖，然后使用npm run dev 在谷歌页面是能打开的 然后我使用了yarn build build出来的页面在任何浏览器打开index.html都是空白的 请问？

**Comment by Littly** [comment]
受制于webpack-dev-server的，dev模式暂时不支持ie8；
build模式下，生成的文件资源路径都已经被替换 需要根据实际情况调整[config/webpack.config.base.js](https://github.com/NervJS/nerv-webpack-boilerplate/blob/ac57a7e4c33baa7a7dbffbff93868430408dadf4/config/webpack.config.base.js#L13)文件的publicPath字段😊
