### ISSUE TITLE
IE8依旧有问题

### ISSUE THREAD

**Issue by fred7BF** [NervJS/nerv-webpack-boilerplate#6]
dev模式下chrome能用，IE8不能用,build的文件都用不了

**Comment by Littly** [comment]
dev模式使用了webpack-dev-server，暂时不支持ie8的喔。
build的文件用不了，有木有具体的问题描述呢？

**Comment by magicapple** [comment]
build出来的文件路径为'/js/xxx'，需要起一个服务才能查看，不能直接打开，或者将路径改成相对路径。
测试了build文件能在ie8正常使用。

**Comment by YutHelloWorld** [comment]
贴一篇文章：https://medium.com/react-university/getting-react-to-run-on-ie8-bfc0a3e7543a
要在IE8下看的话直接`yarn deploy`
